FROM python:3.9-slim

WORKDIR /app

# Install required packages
COPY app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY app/proxy.py .

# Create logs directory
RUN mkdir -p /app/logs

CMD ["python", "proxy.py"]