services:
  influxdb:
    image: influxdb:2
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb2-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb2-admin-password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb2-admin-token
      DOCKER_INFLUXDB_INIT_ORG: aviation
      DOCKER_INFLUXDB_INIT_BUCKET: flights
    secrets:
      - influxdb2-admin-username
      - influxdb2-admin-password
      - influxdb2-admin-token
    volumes:
      - influxdb2-data:/var/lib/influxdb2
      - influxdb2-config:/etc/influxdb2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER__FILE: /run/secrets/grafana-admin-user
      GF_SECURITY_ADMIN_PASSWORD__FILE: /run/secrets/grafana-admin-password  
      GF_PROVISIONING_PATH: /etc/grafana/provisioning          
    env_file:
      - .env.grafana
    depends_on:
       influxdb:
        condition: service_healthy
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    secrets:
      - grafana-admin-user
      - grafana-admin-password

  proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    container_name: opensky_proxy
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN_FILE=/run/secrets/influxdb2-admin-token
      - INFLUXDB_ORG=aviation
      - INFLUXDB_BUCKET=flights
      - OPENSKY_API_URL=https://opensky-network.org/api/states/all
    secrets:
      - influxdb2-admin-token
    restart: unless-stopped
    depends_on:
      influxdb:
        condition: service_healthy

secrets:
  influxdb2-admin-username:
    file: .env.influxdb2-admin-username
  influxdb2-admin-password:
    file: .env.influxdb2-admin-password
  influxdb2-admin-token:
    file: .env.influxdb2-admin-token
  grafana-admin-user:
    file: .env.grafana-admin-user
  grafana-admin-password:
    file: .env.grafana-admin-password

volumes:
  influxdb2-data:
  influxdb2-config:
  grafana-data: