{
 "title": "Real Time Stats by Country",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "country_selection",
    "label": "country_selection ",
    "query": {
     "query": "from(bucket: \"flights\")\r\n  |> range(start: 1970-01-01T00:00:00Z)\r\n  |> filter(fn: (r) => r._measurement == \"flights\")\r\n  |> keep(columns: [\"origin_country\"])\r\n  |> distinct(column: \"origin_country\")"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Airport congestion",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"flights\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"flights\")\r\n  |> filter(fn: (r) => r[\"origin_country\"] == \"${country_selection}\")\r\n  |> filter(fn: (r) => r._field == \"on_ground\")\r\n  |> filter(fn: (r) => r._value == true)\r\n  |> group() \r\n  |> count()\r\n  |> last()\r\n  |> keep(columns: [\"_value\"])  "
    }
   ]
  },
  {
   "type": "geomap",
   "gridPos": { "h": 18, "w": 16, "x": 7, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"flights\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"latitude\" or r._field == \"longitude\")\r\n  |> filter(fn: (r) => r[\"origin_country\"] == \"${country_selection}\")\r\n  |> group(columns: [\"icao24\", \"origin_country\"])\r\n  |> pivot(rowKey: [\"_time\", \"icao24\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => exists r.latitude and exists r.longitude)\r\n  |> top(n: 1, columns: [\"_time\"])\r\n  |> group()\r\n  |> yield(name: \"flights_position\")"
    }
   ]
  },
  {
   "title": "Active Flights",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"flights\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"country_stats\")\r\n  |> filter(fn: (r) => r[\"country\"] == \"${country_selection}\")\r\n  |> filter(fn: (r) => r._field == \"flight_count\")\r\n  |> last()\r\n  |> drop(columns: [\"_measurement\", \"_field\", \"_start\", \"_stop\", \"country\"])"
    }
   ]
  },
  {
   "title": "TOP 5",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 3, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"flights\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"country_stats\")\r\n  |> filter(fn: (r) => r._field == \"flight_count\")\r\n  |> group(columns: [\"country\"])\r\n  |> last()\r\n  |> group()\r\n  |> sort(columns: [\"_value\"], desc: true)\r\n  |> limit(n: 5)\r\n  |> rename(columns: {_value: \"Flights\", country: \"Country\"})\r\n  |> keep(columns: [\"Country\", \"Flights\", \"_time\"])"
    }
   ]
  },
  {
   "title": "Airplanes in the air/on the ground",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 15, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"flights\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"flights\")\r\n  |> filter(fn: (r) => r[\"origin_country\"] == \"${country_selection}\")\r\n  |> filter(fn: (r) => r._field == \"on_ground\")\r\n  |> last()\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      status: if r._value == true then \"On Ground\" else \"In Air\"\r\n  }))\r\n  |> group(columns: [\"status\"])\r\n  |> count()\r\n  |> keep(columns: [\"status\", \"_value\"])"
    }
   ]
  }
 ]
}