{
 "title": "Track Plane Stats",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "icao24_selection",
    "label": "icao24_selection",
    "query": {
     "query": "from(bucket: \"flights\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"flights\")\n  |> keep(columns: [\"icao24\"])\n  |> distinct(column: \"icao24\")"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current Altitude",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"flights\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"flights\")\r\n  |> filter(fn: (r) => r[\"icao24\"] == \"${icao24_selection}\")\r\n  |> filter(fn: (r) => r._field == \"altitude\")\r\n  |> last()"
    }
   ]
  },
  {
   "type": "geomap",
   "gridPos": { "h": 20, "w": 12, "x": 8, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"flights\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"latitude\" or r._field == \"longitude\")\n  |> filter(fn: (r) => r[\"icao24\"] == \"${icao24_selection}\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => exists r.latitude and exists r.longitude)\n  |> yield(name: \"aircraft_path\")"
    }
   ]
  },
  {
   "title": "Current Velocity",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"flights\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"flights\")\r\n  |> filter(fn: (r) => r[\"icao24\"] == \"${icao24_selection}\")\r\n  |> filter(fn: (r) => r._field == \"velocity\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Current Vertical Rate",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"flights\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"flights\")\r\n  |> filter(fn: (r) => r[\"icao24\"] == \"${icao24_selection}\")\r\n  |> filter(fn: (r) => r._field == \"vertical_rate\")\r\n  |> last()"
    }
   ]
  }
 ]
}